Repository Countly/countly-sdk-documentation, pull requests merged in 2023-08, with the labels that each got.

#368 [iOS] A/B Testing Variant Information
  ios/current.md
  ios/next.md
Labels: SDK

#332 Symbolication section
  a_deeper_look_at_sdk_concepts/current.md
Labels: Structure, Advanced SDK

#370 [Android] Warning removed
  android/next.md
Labels: SDK, Fix
