Repository Countly/countly-sdk-documentation, pull requests merged in 2023-04, with the labels that each got.

#338 [iOS] XCode settings for log visibility
  ios/next.md
Labels: SDK

#329 iOS Doc: changeDeviceIDWithMerge and changeDeviceIDWithoutMerge added
  ios/next.md
Labels: SDK

#328 [Web] User feedback changes for new API
  web/next.md
Labels: SDK

#343 Kotlin for login
  getting_started/current.md
Labels: Getting Started, Linting

#342 [All SDKs] Where to find logs
  android/next.md
  flutter/next.md
  ios/next.md
  react_native_bridged/next.md
  unity/next.md
  web/next.md
Labels: SDK

#346 [Android, Flutter] Package Updates and some fixes
  android/next.md
  flutter/next.md
Labels: SDK, Structure, Fix

#335 [Flutter] User Consent
  flutter/next.md
Labels: SDK, Structure

#347 [iOS] server conf
  ios/current.md
  ios/next.md
Labels: SDK

#348 [Android] Server config
  android/current.md
  android/next.md
Labels: SDK

#330 [RN] Config object documentation
  react_native_bridged/next.md
Labels: SDK
