Repository Countly/countly-sdk-documentation, pull requests merged in 2023-10, with the labels that each got.

#401 [Java, Doc] update version and update countly init call
  java/next.md
Labels: SDK

#389 [Java] feat: new event calls
  java/next.md
Labels: SDK

#402 [Java, Doc] Document the feedback widgets
  java/next.md
Labels: SDK

#405 [RN] New structure
  react_native_bridged/next.md
Labels: SDK, Structure, Fix

#407 [RN] Manual Reporting
  react_native_bridged/next.md
Labels: SDK, Linting, Fix

#403 [Web] New structure implementation
  documentation_structure.md
  web/next.md
Labels: SDK, Linting, Structure, Fix

#384 [Flutter] Remote config changes
  flutter/next.md
Labels: SDK

#388 [Android,iOS,Flutter] Added get&enroll method information
  android/next.md
  flutter/next.md
  ios/next.md
Labels: SDK

#421 [Flutter,Android,iOS] Drop old requests
  android/current.md
  android/next.md
  flutter/current.md
  flutter/next.md
  ios/current.md
  ios/next.md
Labels: SDK

#424 [Java, doc] add only supported image type to doc
  java/next.md
Labels: SDK

#426 [Android, Doc] Add deeper look link to ssl cert pinning
  android/next.md
Labels: SDK
