Repository Countly/countly-sdk-documentation, pull requests merged in 2023-09, with the labels that each got.

#373 Opt In flag and URL info
  sdk_dev_guide/curent.md
Labels: SDK Guide

#372 [Flutter] Improvement suggestions
  flutter/next.md
Labels: SDK, Linting, Fix

#378 [Documentation Structure] SDK doc structure info added
  documentation_structure.md
Labels: Structure

#382 Adding new header IDs
  cpp/current.md
  java/current.md
  nodejs/current.md
  unity/current.md
  web/current.md
  windows/current.md
Labels: SDK, Structure

#383 [Flutter] Updated Sessions
  flutter/next.md
Labels: SDK

#387 [SDKs] Copied Header IDs to next.md
  cpp/next.md
  java/next.md
  nodejs/next.md
  unity/next.md
  web/next.md
  windows/next.md
Labels: Structure, Fix

#394 Fix java,windows and nodejs links
  java/next.md
  nodejs/next.md
  windows/next.md
Labels: SDK, Fix

#395 Broken Links Fixed and Updated
  unity/next.md
Labels: Fix

#398 Getting started links
  getting_started/current.md
Labels: Fix

#396 Fixed links
  cpp/next.md
Labels: Fix
