Repository Countly/countly-sdk-documentation, pull requests merged in 2023-07, with the labels that each got.

#364 updating the docs
  react_native_bridged/next.md
Labels: SDK, Release, Structure, Fix

#363 [iOS] New RC methods
  ios/next.md
Labels: SDK, Structure

#366 [Flutter,Android] Added registerdownloadcallbacks
  android/current.md
  android/next.md
  flutter/current.md
  flutter/next.md
Labels: SDK, Fix

#345 [Web] APM
  web/next.md
Labels: SDK, Structure, Fix
